# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/ndev-inite-test',
                'doc_host': 'https://rehas.github.io',
                'git_url': 'https://github.com/rehas/ndev-inite-test',
                'lib_path': 'ndev_inite_test'},
  'syms': {'ndev_inite_test.core': {'ndev_inite_test.core.foo': ('core.html#foo', 'ndev_inite_test/core.py')}}}
